### PR TITLE
Changes to project_2d.py to allow for different source bins

### PR DESCRIPTION
**Pull request by andrejdvornik**
... but not complete cross-correlations.

Motivation: if a passed power spectra is a cross-correlation between a tracer and a matter (for instance galaxy-galaxy lensing) then if the spectrum is passed for each lens bin separately, in most cases the underlying matter part will stay the same, thus can be correlated with a different tomographic bin for the source distribution.

This change hopefully accounts for that, but will still not allow the cross-correlations if the power spectrum is the auto-correlation in the first place. This should still also be ok for the IA and magnification cases.

Apart from this, the changes to allow for general clustering work perfectly. I can produce Cells for any power spectrum generated in this case using a HOD based halo model.

### CODE REVIEW

**Comment by joezuntz** [comment]
The failing checks are conda-related, not to do with your changes. Let me fix them in main!

**Comment by joezuntz** [comment]
Could you merge the main branch into this PR?  I have added various fixes to the installation system that should hopefully fix these failures.

**Comment by andrejdvornik** [comment]
Merged the main now, sorry for a silence.

**Comment by joezuntz** [comment]
Thanks!

**Pull request merged**
